language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-turtle' ]; then cd .. && eval "mv $currentfolder generator-turtle" && cd generator-turtle; fi

